version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: lakedata
      POSTGRES_USER: root
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 5001:8080
